branch-defaults:
  aws-deployment:
    environment: cheerup-env
    group_suffix: null
  develop:
    environment: cheerup-env
  join-a-event:
    environment: cheerup-env
  test-deployment:
    environment: cheerup-env
global:
  application_name: cheerup
  branch: null
  default_ec2_keyname: cheerup-se-project
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
